destination: ./_site
auto:        false
lsi:         false
safe: false
server_port: 4000
permalink: /:year/:month/:title/
pygments: true
markdown: redcarpet
paginate: 20
paginate_path: "/page:num"
#maruku:
#  use_tex:    false
#  use_divs:   false
#  png_dir:    images/latex
#  png_url:    /images/latex
  
#exclude: ["Rakefile", "w.psd", "header.psd"]
